###############################################
# Author: Christos Faloutsos and Chenying Hou
# Date: Oct. 2014
###############################################

demo:
	perl mkboxcount.pl -q2 -r0.0000000001 -R10000000000 -s10 ../data/mystery1 > result


	
